"""V5.9.1 frozen real-company seed deck for Deal Studio.

This module is a build-time snapshot only. It does not fetch market data,
does not call plugins, and does not auto-refresh source values at runtime.
Financial fields are USD millions, shares are diluted weighted-average shares
in millions, and share_price is USD per share from a separate quote snapshot.
"""

from __future__ import annotations

from typing import Any


_ARENA_TIER_META = {
    "gold": ("Legendary", "金 / 传奇"),
    "red": ("Elite", "红 / 精英"),
    "blue": ("Core", "蓝 / 核心"),
    "green": ("Specialist", "绿 / 专精"),
    "white": ("Basic", "白 / 基础"),
}


def _arena_tier(tier: str, reason: str) -> dict[str, str]:
    """Return frozen Arena-only card rarity metadata."""
    label, name_cn = _ARENA_TIER_META[tier]
    return {
        "arena_tier": tier,
        "arena_tier_label": label,
        "arena_tier_name_cn": name_cn,
        "arena_tier_reason": reason,
    }


def _source(accession: str, fiscal_period: str, price_time: str, notes: str, confidence: str) -> dict[str, str]:
    return {
        "source": "SEC EDGAR + Stooq",
        "source_document_or_provider": f"SEC companyfacts / {accession}; Stooq quote",
        "fiscal_period_or_as_of_date": f"{fiscal_period}; price snapshot {price_time}",
        "as_of_date": "2026-06-04",
        "notes": notes,
        "confidence": confidence,
    }


def _wave1_source(
    ticker: str,
    cik: str,
    accession: str,
    fiscal_period: str,
    notes: str,
    confidence: str,
    field_sources: dict[str, str],
) -> dict[str, Any]:
    accession_compact = accession.replace("-", "")
    cik_compact = str(int(cik))
    return {
        "source": "SEC EDGAR + Yahoo Finance",
        "source_document_or_provider": (
            f"SEC companyfacts / {accession}; SEC 10-K; Yahoo Finance chart"
        ),
        "fiscal_period_or_as_of_date": (
            f"{fiscal_period}; price snapshot 2026-06-04"
        ),
        "as_of_date": "2026-06-04",
        "notes": notes,
        "confidence": confidence,
        "filing_url": (
            "https://www.sec.gov/Archives/edgar/data/"
            f"{cik_compact}/{accession_compact}/"
        ),
        "companyfacts_url": (
            f"https://data.sec.gov/api/xbrl/companyfacts/CIK{cik}.json"
        ),
        "quote_url": (
            "https://query1.finance.yahoo.com/v8/finance/chart/"
            f"{ticker}?period1=1780444800&period2=1780790400&interval=1d"
        ),
        "field_sources": dict(field_sources),
    }


WAVE2_DEFERRED_CANDIDATES: dict[str, str] = {
    "SNOW": "Deferred: GAAP profitability and EBITDA presentation remain poor fits for the A/D first pass.",
    "PLTR": "Deferred: strong gameplay recognition, but valuation and profitability normalization need a separate review.",
    "DDOG": "Deferred: GAAP profitability and stock-compensation effects make the current A/D snapshot less representative.",
    "JPM": "Deferred: bank balance-sheet and regulatory-capital economics are outside the current company-card model.",
    "BAC": "Deferred: bank balance-sheet and regulatory-capital economics are outside the current company-card model.",
    "BLK": "Deferred: asset-manager AUM and fee-economics fields need a dedicated financial-services card treatment.",
    "AXP": "Deferred: card-network and lending economics are mixed and need a financial-services-specific normalization.",
    "BA": "Deferred: program accounting, abnormal charges, and negative earnings remain difficult to explain in the first-pass engine.",
    "GE": "Deferred: recent portfolio separation and comparability changes need a dedicated post-spin source review.",
    "DE": "Deferred: industrial operations and captive-finance debt require a cleaner segment debt convention.",
    "HON": "Deferred: portfolio-transition comparability should be revisited after the announced separation work is clearer.",
    "CMCSA": "Deferred: cable, media, and theme-park mix is usable but lower priority than the selected industry gaps.",
    "T": "Deferred: telecom lease, spectrum, and debt conventions need a dedicated normalization pass.",
    "TMUS": "Deferred: telecom lease, spectrum, and debt conventions need a dedicated normalization pass.",
}


REAL_SEED_COMPANY_CARDS: list[dict[str, Any]] = [
    {
        "id": "aapl",
        "ticker": "AAPL",
        "name": "Apple Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Consumer Electronics",
        "revenue": 416161.0,
        "ebitda": 144748.0,
        "net_income": 112010.0,
        "cash": 35934.0,
        "debt": 98657.0,
        "shares": 15004.697,
        "share_price": 311.01,
        **_arena_tier("gold", "Global platform, iconic recognition, and strong deck data."),
        "tags": {
            "industry_group": "consumer_electronics_ecosystem",
            "strategic_tags": ["platform", "hardware", "services", "ecosystem", "consumer"],
            "sensitive_sectors": ["data", "consumer_technology"],
            "jurisdiction": "US",
            "market_position": "mega_cap_global_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0000320193-25-000079",
            "FY ended 2025-09-27",
            "2026-06-04 16:08 ET",
            "FY2025 SEC facts tie out clean; debt should be LT debt plus commercial paper, not LT debt alone.",
            "medium",
        ),
    },
    {
        "id": "msft",
        "ticker": "MSFT",
        "name": "Microsoft Corporation",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Software / Cloud",
        "revenue": 281724.0,
        "ebitda": 150528.0,
        "net_income": 101832.0,
        "cash": 30242.0,
        "debt": 43151.0,
        "shares": 7465.0,
        "share_price": 433.70,
        **_arena_tier("gold", "Global enterprise platform with exceptional recognition and data depth."),
        "tags": {
            "industry_group": "enterprise_software_cloud",
            "strategic_tags": ["software", "cloud", "AI", "enterprise", "platform"],
            "sensitive_sectors": ["data", "AI"],
            "jurisdiction": "US",
            "market_position": "mega_cap_global_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0000950170-25-100235",
            "FY ended 2025-06-30",
            "2026-06-04 16:08 ET",
            "FY2025 revenue/net income/diluted shares/cash/debt tie out clean; EBITDA is operating income plus depreciation.",
            "high",
        ),
    },
    {
        "id": "googl",
        "ticker": "GOOGL",
        "name": "Alphabet Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Communication Services",
        "industry": "Internet Content / Cloud / Ads",
        "revenue": 402836.0,
        "ebitda": 150175.0,
        "net_income": 132170.0,
        "cash": 30708.0,
        "debt": 49085.0,
        "shares": 12230.0,
        "share_price": 365.39,
        **_arena_tier("gold", "Global search, ads, and cloud platform with major table influence."),
        "tags": {
            "industry_group": "search_ads_cloud",
            "strategic_tags": ["search", "ads", "cloud", "AI", "platform"],
            "sensitive_sectors": ["data", "AI"],
            "jurisdiction": "US",
            "market_position": "mega_cap_global_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0001652044-26-000018",
            "FY ended 2025-12-31",
            "2026-06-04 16:08 ET",
            "FY2025 core fields tie out clean; use total LT debt tag and retain note that current/noncurrent debt subtotal differs slightly.",
            "medium",
        ),
    },
    {
        "id": "amzn",
        "ticker": "AMZN",
        "name": "Amazon.com, Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Consumer Discretionary",
        "industry": "E-commerce / Cloud / Logistics",
        "revenue": 716924.0,
        "ebitda": 145731.0,
        "net_income": 77670.0,
        "cash": 86810.0,
        "debt": 69291.0,
        "shares": 10827.0,
        "share_price": 254.215,
        **_arena_tier("gold", "Global commerce, cloud, and logistics platform with broad gameplay reach."),
        "tags": {
            "industry_group": "ecommerce_cloud_logistics",
            "strategic_tags": ["ecommerce", "cloud", "logistics", "marketplace", "retail"],
            "sensitive_sectors": ["data", "marketplace"],
            "jurisdiction": "US",
            "market_position": "mega_cap_global_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0001018724-26-000004",
            "FY ended 2025-12-31",
            "2026-06-04 16:08 ET",
            "FY2025 core fields tie out clean; debt includes LT debt plus disclosed short-term borrowings.",
            "medium",
        ),
    },
    {
        "id": "meta",
        "ticker": "META",
        "name": "Meta Platforms, Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Communication Services",
        "industry": "Social Platforms / Ads",
        "revenue": 200966.0,
        "ebitda": 101892.0,
        "net_income": 60458.0,
        "cash": 35873.0,
        "debt": 58744.0,
        "shares": 2574.0,
        "share_price": 638.10,
        **_arena_tier("gold", "Global social and ads platform with high recognition and table influence."),
        "tags": {
            "industry_group": "social_ads_platform",
            "strategic_tags": ["social", "ads", "AI", "platform"],
            "sensitive_sectors": ["data", "social_media"],
            "jurisdiction": "US",
            "market_position": "mega_cap_global_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0001628280-26-003942",
            "FY ended 2025-12-31",
            "2026-06-04 16:08 ET",
            "FY2025 core fields tie out clean; debt is noncurrent long-term debt with no separate short-term debt found in this tie-out.",
            "high",
        ),
    },
    {
        "id": "nvda",
        "ticker": "NVDA",
        "name": "NVIDIA Corporation",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Semiconductors",
        "revenue": 215938.0,
        "ebitda": 133230.0,
        "net_income": 120067.0,
        "cash": 10605.0,
        "debt": 8468.0,
        "shares": 24514.0,
        "share_price": 211.72,
        **_arena_tier("gold", "Globally recognized AI infrastructure leader with exceptional deck impact."),
        "tags": {
            "industry_group": "semiconductors_ai_accelerators",
            "strategic_tags": ["semiconductors", "AI", "hardware", "datacenter", "accelerators"],
            "sensitive_sectors": ["semiconductors", "AI"],
            "jurisdiction": "US",
            "market_position": "mega_cap_global_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0001045810-26-000021",
            "FY ended 2026-01-25",
            "2026-06-04 16:08 ET",
            "FY2026 core fields tie out clean; debt is current plus noncurrent long-term debt.",
            "high",
        ),
    },
    {
        "id": "dis",
        "ticker": "DIS",
        "name": "The Walt Disney Company",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Communication Services",
        "industry": "Entertainment / Media",
        "revenue": 94425.0,
        "ebitda": 22877.0,
        "net_income": 12404.0,
        "cash": 5695.0,
        "debt": 42026.0,
        "shares": 1811.0,
        "share_price": 101.28,
        **_arena_tier("blue", "Mature global media and experiences card with a distinct gameplay role."),
        "tags": {
            "industry_group": "media_entertainment_content",
            "strategic_tags": ["content", "media", "streaming", "parks", "entertainment"],
            "sensitive_sectors": ["media", "content"],
            "jurisdiction": "US",
            "market_position": "global_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0001744489-25-000155",
            "FY ended 2025-09-27",
            "2026-06-04 16:08 ET",
            "FY2025 core fields tie out clean; debt is current plus noncurrent long-term debt and EBITDA is operating income plus D&A.",
            "high",
        ),
    },
    {
        "id": "hd",
        "ticker": "HD",
        "name": "The Home Depot, Inc.",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Consumer Discretionary",
        "industry": "Home Improvement Retail",
        "revenue": 164683.0,
        "ebitda": 24404.0,
        "net_income": 14156.0,
        "cash": 1389.0,
        "debt": 53861.0,
        "shares": 995.0,
        "share_price": 314.72,
        **_arena_tier("blue", "Representative large-scale retail card with complete, stable deck data."),
        "tags": {
            "industry_group": "home_improvement_retail",
            "strategic_tags": ["retail", "home_improvement", "professional_customers", "housing"],
            "sensitive_sectors": ["consumer", "housing"],
            "jurisdiction": "US",
            "market_position": "us_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0001628280-26-019436",
            "FY ended 2026-02-01",
            "2026-06-04 16:08 ET",
            "FY2026 core fields tie out clean; debt includes LT debt plus commercial paper and excludes lease obligation tags.",
            "medium",
        ),
    },
    {
        "id": "avgo",
        "ticker": "AVGO",
        "name": "Broadcom Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Semiconductors / Infrastructure Software",
        "revenue": 63887.0,
        "ebitda": 34120.0,
        "net_income": 23126.0,
        "cash": 16178.0,
        "debt": 65136.0,
        "shares": 4853.0,
        "share_price": 419.02,
        **_arena_tier("red", "Category-leading semiconductor and infrastructure platform with strong deal narratives."),
        "tags": {
            "industry_group": "semiconductor_networking_infrastructure",
            "strategic_tags": [
                "semiconductors",
                "networking",
                "infrastructure software",
                "AI infrastructure",
                "enterprise infrastructure",
            ],
            "sensitive_sectors": ["semiconductors", "AI"],
            "jurisdiction": "US",
            "market_position": "category_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0001730168-25-000121",
            "FY ended 2025-11-02",
            "2026-06-04 22:00 ET",
            "FY2025 SEC facts tie out clean; EBITDA is operating income plus depreciation and acquired-intangible amortization; debt uses short-term debt plus long-term debt carrying amount, excluding lease obligations.",
            "high",
        ),
    },
    {
        "id": "orcl",
        "ticker": "ORCL",
        "name": "Oracle Corporation",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Database / Enterprise Software / Cloud",
        "revenue": 57399.0,
        "ebitda": 23852.0,
        "net_income": 12443.0,
        "cash": 10786.0,
        "debt": 92568.0,
        "shares": 2866.0,
        "share_price": 236.36,
        **_arena_tier("red", "Category-leading database and enterprise platform with strong transaction presence."),
        "tags": {
            "industry_group": "database_enterprise_cloud_infrastructure",
            "strategic_tags": ["database", "cloud", "enterprise software", "AI infrastructure", "applications"],
            "sensitive_sectors": ["data", "AI"],
            "jurisdiction": "US",
            "market_position": "category_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0000950170-25-087926",
            "FY ended 2025-05-31",
            "2026-06-04 22:00 ET",
            "FY2025 core fields tie out; cash excludes marketable securities; debt is notes payable and other borrowings current plus non-current, with finance lease liabilities excluded.",
            "medium",
        ),
    },
    {
        "id": "crm",
        "ticker": "CRM",
        "name": "Salesforce, Inc.",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Enterprise SaaS / CRM Software",
        "revenue": 41525.0,
        "ebitda": 11962.0,
        "net_income": 7457.0,
        "cash": 7327.0,
        "debt": 14439.0,
        "shares": 956.0,
        "share_price": 188.79,
        **_arena_tier("blue", "Mature enterprise SaaS platform and representative core deck card."),
        "tags": {
            "industry_group": "enterprise_saas_customer_platform",
            "strategic_tags": ["enterprise software", "SaaS", "CRM", "AI agents", "data platform"],
            "sensitive_sectors": ["data", "AI"],
            "jurisdiction": "US",
            "market_position": "category_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0001108524-26-000060",
            "FY ended 2026-01-31",
            "2026-06-04 22:00 ET",
            "FY2026 revenue/net income/diluted shares tie out; cash excludes marketable securities; EBITDA is operating income plus D&A, with Informatica acquisition noted for comparability.",
            "medium",
        ),
    },
    {
        "id": "cost",
        "ticker": "COST",
        "name": "Costco Wholesale Corporation",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Consumer Staples",
        "industry": "Membership Warehouse Retail",
        "revenue": 275235.0,
        "ebitda": 12809.0,
        "net_income": 8099.0,
        "cash": 14161.0,
        "debt": 5788.0,
        "shares": 444.803,
        "share_price": 972.35,
        **_arena_tier("red", "Highly recognizable membership retail platform with strong market presence."),
        "tags": {
            "industry_group": "membership_warehouse_retail",
            "strategic_tags": ["retail", "membership", "consumer staples", "warehouse", "private label"],
            "sensitive_sectors": ["consumer"],
            "jurisdiction": "US",
            "market_position": "us_membership_retail_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0000909832-25-000101",
            "FY ended 2025-08-31",
            "2026-06-04 22:00 ET",
            "FY2025 SEC facts tie out clean; EBITDA is operating income plus D&A; debt is current plus noncurrent long-term debt and excludes finance lease liabilities.",
            "high",
        ),
    },
    {
        "id": "cat",
        "ticker": "CAT",
        "name": "Caterpillar Inc.",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Industrials",
        "industry": "Construction / Mining Machinery",
        "revenue": 67589.0,
        "ebitda": 13389.0,
        "net_income": 8882.0,
        "cash": 9980.0,
        "debt": 43330.0,
        "shares": 472.3,
        "share_price": 940.29,
        **_arena_tier("blue", "Representative industrial leader and dependable core infrastructure card."),
        "tags": {
            "industry_group": "industrial_machinery_equipment",
            "strategic_tags": ["industrial", "machinery", "construction", "mining", "infrastructure"],
            "sensitive_sectors": ["industrial", "infrastructure"],
            "jurisdiction": "US",
            "market_position": "industrial_equipment_leader",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0000018230-26-000008",
            "FY ended 2025-12-31",
            "2026-06-04 22:00 ET",
            "FY2025 revenue/net income/shares/cash tie out; EBITDA is operating income plus D&A; debt should be read with note that Caterpillar has machinery and financial-products debt presentation.",
            "medium",
        ),
    },
    {
        "id": "xom",
        "ticker": "XOM",
        "name": "Exxon Mobil Corporation",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Energy",
        "industry": "Integrated Oil & Gas",
        "revenue": 332238.0,
        "ebitda": 67864.0,
        "net_income": 28844.0,
        "cash": 10681.0,
        "debt": 43537.0,
        "shares": 4305.0,
        "share_price": 152.04,
        **_arena_tier("red", "Integrated energy major with strong market presence and deal-table capacity."),
        "tags": {
            "industry_group": "integrated_oil_gas_energy",
            "strategic_tags": ["energy", "oil and gas", "upstream", "downstream", "chemicals"],
            "sensitive_sectors": ["energy", "climate"],
            "jurisdiction": "US",
            "market_position": "integrated_energy_major",
            "state_linked": False,
        },
        "source_meta": _source(
            "10-K accession 0000034088-26-000045",
            "FY ended 2025-12-31",
            "2026-06-04 22:01 ET",
            "FY2025 revenue/net income/cash/share count tie out; EBITDA is derived from income before tax plus interest expense plus depreciation/depletion, not operating income plus D&A; debt includes current debt plus long-term debt.",
            "medium",
        ),
    },
    {
        "id": "v",
        "ticker": "V",
        "name": "Visa Inc.",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Financials",
        "industry": "Payments Network",
        "revenue": 40000.0,
        "ebitda": 25214.0,
        "net_income": 20058.0,
        "cash": 17164.0,
        "debt": 25171.0,
        "shares": 1966.0,
        "share_price": 320.18,
        **_arena_tier("gold", "Global payments network with iconic recognition and exceptional table reach."),
        "tags": {
            "industry_group": "payments_networks",
            "strategic_tags": ["payments", "network", "fintech infrastructure", "platform", "consumer"],
            "sensitive_sectors": ["payments", "financial infrastructure", "data"],
            "jurisdiction": "US",
            "market_position": "global_payments_network_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "V",
            "0001403161",
            "0001403161-25-000089",
            "FY ended 2025-09-30",
            "FY2025 revenue, net income, cash, and debt tie to SEC facts. EBITDA is operating income plus D&A. Diluted shares use the 10-K EPS table's class-converted total because companyfacts omits the aggregate diluted-share fact.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts current plus noncurrent long-term debt",
                "shares": "SEC 10-K diluted weighted-average shares table, all classes converted",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "ma",
        "ticker": "MA",
        "name": "Mastercard Incorporated",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Financials",
        "industry": "Payments Network",
        "revenue": 32791.0,
        "ebitda": 20040.0,
        "net_income": 14968.0,
        "cash": 10566.0,
        "debt": 19000.0,
        "shares": 906.0,
        "share_price": 481.76,
        **_arena_tier("gold", "Global payments platform with broad recognition and major transaction-table influence."),
        "tags": {
            "industry_group": "payments_networks",
            "strategic_tags": ["payments", "network", "fintech infrastructure", "platform", "consumer"],
            "sensitive_sectors": ["payments", "financial infrastructure", "data"],
            "jurisdiction": "US",
            "market_position": "global_payments_network_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "MA",
            "0001141391",
            "0001141391-26-000013",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A; debt is current plus noncurrent long-term debt and excludes lease liabilities.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationAndAmortization",
                "net_income": "SEC companyfacts us-gaap:ProfitLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts current plus noncurrent long-term debt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "adbe",
        "ticker": "ADBE",
        "name": "Adobe Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Creative / Document Software",
        "revenue": 23769.0,
        "ebitda": 9524.0,
        "net_income": 7130.0,
        "cash": 5431.0,
        "debt": 6210.0,
        "shares": 427.0,
        "share_price": 258.42,
        **_arena_tier("red", "Category-defining creative and document software platform with strong gameplay identity."),
        "tags": {
            "industry_group": "creative_document_software",
            "strategic_tags": ["software", "SaaS", "creative", "documents", "AI"],
            "sensitive_sectors": ["data", "AI"],
            "jurisdiction": "US",
            "market_position": "category_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "ADBE",
            "0000796343",
            "0000796343-26-000003",
            "FY ended 2025-11-28",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A; debt uses the reported long-term carrying amount.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:LongTermDebt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "now",
        "ticker": "NOW",
        "name": "ServiceNow, Inc.",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Enterprise Workflow Software",
        "revenue": 13278.0,
        "ebitda": 2562.0,
        "net_income": 1748.0,
        "cash": 3726.0,
        "debt": 1491.0,
        "shares": 1046.691,
        "share_price": 119.36,
        **_arena_tier("red", "Enterprise workflow platform with a distinct cloud and AI deal-table role."),
        "tags": {
            "industry_group": "enterprise_workflow_platform",
            "strategic_tags": ["enterprise software", "SaaS", "workflow", "cloud", "AI"],
            "sensitive_sectors": ["data", "AI"],
            "jurisdiction": "US",
            "market_position": "category_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "NOW",
            "0001373715",
            "0001373715-26-000007",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A; debt is the noncurrent convertible-notes carrying amount. Shares and quote are post-split.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:ConvertibleLongTermNotesPayable",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "panw",
        "ticker": "PANW",
        "name": "Palo Alto Networks, Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Cybersecurity Platform",
        "revenue": 9221.5,
        "ebitda": 1586.3,
        "net_income": 1133.9,
        "cash": 2268.6,
        "debt": 0.0,
        "shares": 709.3,
        "share_price": 279.25,
        **_arena_tier("red", "Cybersecurity platform leader with high thematic and strategic table relevance."),
        "tags": {
            "industry_group": "cybersecurity_platform",
            "strategic_tags": ["cybersecurity", "security", "cloud", "network", "AI"],
            "sensitive_sectors": ["cybersecurity", "data", "AI"],
            "jurisdiction": "US",
            "market_position": "category_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "PANW",
            "0001327567",
            "0001327567-25-000027",
            "FY ended 2025-07-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A; reported convertible debt was zero after repayment, while lease liabilities remain excluded.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:ConvertibleDebtCurrent",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "amd",
        "ticker": "AMD",
        "name": "Advanced Micro Devices, Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Semiconductor Design",
        "revenue": 34639.0,
        "ebitda": 6515.0,
        "net_income": 4335.0,
        "cash": 5539.0,
        "debt": 3222.0,
        "shares": 1636.0,
        "share_price": 523.20,
        **_arena_tier("red", "Leading compute-chip designer with a major AI and datacenter gameplay role."),
        "tags": {
            "industry_group": "semiconductor_design_compute",
            "strategic_tags": ["semiconductors", "CPU", "GPU", "AI", "datacenter"],
            "sensitive_sectors": ["semiconductors", "AI"],
            "jurisdiction": "US",
            "market_position": "category_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "AMD",
            "0000002488",
            "0000002488-26-000018",
            "FY ended 2025-12-27",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus depreciation and acquired-intangible amortization; debt is current plus noncurrent long-term debt.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus depreciation and intangible amortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts current plus noncurrent long-term debt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "qcom",
        "ticker": "QCOM",
        "name": "QUALCOMM Incorporated",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Wireless Semiconductors / IP",
        "revenue": 44284.0,
        "ebitda": 13957.0,
        "net_income": 5541.0,
        "cash": 5520.0,
        "debt": 14811.0,
        "shares": 1105.0,
        "share_price": 242.57,
        **_arena_tier("blue", "Representative wireless semiconductor and licensing platform with complete deck data."),
        "tags": {
            "industry_group": "semiconductor_wireless_ip",
            "strategic_tags": ["semiconductors", "wireless", "mobile", "licensing", "edge AI"],
            "sensitive_sectors": ["semiconductors", "communications", "AI"],
            "jurisdiction": "US",
            "market_position": "category_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "QCOM",
            "0000804328",
            "0000804328-25-000085",
            "FY ended 2025-09-28",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A; debt is noncurrent long-term debt with no current debt reported.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:LongTermDebtNoncurrent",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "amat",
        "ticker": "AMAT",
        "name": "Applied Materials, Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Semiconductor Equipment",
        "revenue": 28368.0,
        "ebitda": 8724.0,
        "net_income": 6998.0,
        "cash": 7241.0,
        "debt": 6555.0,
        "shares": 808.0,
        "share_price": 501.70,
        **_arena_tier("green", "Critical semiconductor-equipment specialist with a focused supply-chain role."),
        "tags": {
            "industry_group": "semiconductor_equipment",
            "strategic_tags": ["semiconductors", "equipment", "materials engineering", "manufacturing"],
            "sensitive_sectors": ["semiconductors", "industrial"],
            "jurisdiction": "US",
            "market_position": "equipment_category_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "AMAT",
            "0000006951",
            "0001628280-25-056742",
            "FY ended 2025-10-26",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A; debt includes short-term borrowings plus noncurrent long-term debt and excludes leases.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts short-term borrowings plus noncurrent long-term debt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "tmo",
        "ticker": "TMO",
        "name": "Thermo Fisher Scientific Inc.",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Health Care",
        "industry": "Life Sciences Tools / Diagnostics",
        "revenue": 44556.0,
        "ebitda": 10526.0,
        "net_income": 6704.0,
        "cash": 9852.0,
        "debt": 42705.0,
        "shares": 378.0,
        "share_price": 482.03,
        **_arena_tier("red", "Life-sciences tools leader with broad strategic reach across research and biopharma."),
        "tags": {
            "industry_group": "healthcare_tools_life_sciences",
            "strategic_tags": ["life sciences", "diagnostics", "lab equipment", "biopharma services"],
            "sensitive_sectors": ["healthcare", "biotechnology"],
            "jurisdiction": "US",
            "market_position": "global_tools_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "TMO",
            "0000097745",
            "0000097745-26-000018",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus depreciation and intangible amortization; debt is current debt plus long-term debt.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus depreciation and intangible amortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:DebtCurrent plus us-gaap:LongTermDebt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "abt",
        "ticker": "ABT",
        "name": "Abbott Laboratories",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Health Care",
        "industry": "Medical Devices / Diagnostics",
        "revenue": 44328.0,
        "ebitda": 11169.0,
        "net_income": 6524.0,
        "cash": 8522.0,
        "debt": 12929.0,
        "shares": 1748.0,
        "share_price": 90.78,
        **_arena_tier("blue", "Mature medtech and diagnostics leader with a broad, representative gameplay role."),
        "tags": {
            "industry_group": "medical_devices_diagnostics",
            "strategic_tags": ["medtech", "diagnostics", "medical devices", "nutrition"],
            "sensitive_sectors": ["healthcare"],
            "jurisdiction": "US",
            "market_position": "global_healthcare_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "ABT",
            "0000001800",
            "0001628280-26-010185",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus depreciation and intangible amortization; debt is current plus noncurrent long-term debt.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus depreciation and intangible amortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts current plus noncurrent long-term debt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "lly",
        "ticker": "LLY",
        "name": "Eli Lilly and Company",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Health Care",
        "industry": "Innovative Pharmaceuticals",
        "revenue": 65179.0,
        "ebitda": 28623.0,
        "net_income": 20640.0,
        "cash": 7268.0,
        "debt": 42503.0,
        "shares": 899.3,
        "share_price": 1125.27,
        **_arena_tier("red", "Globally recognized innovative-pharma leader with an unusually strong thematic role."),
        "tags": {
            "industry_group": "innovative_pharma",
            "strategic_tags": ["pharma", "obesity", "diabetes", "oncology", "R&D"],
            "sensitive_sectors": ["healthcare", "biotechnology"],
            "jurisdiction": "US",
            "market_position": "global_pharma_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "LLY",
            "0000059478",
            "0000059478-26-000013",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is derived from pretax income plus borrowing interest expense plus D&A because the filing uses a functional expense presentation; debt is current plus noncurrent debt.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC pretax income plus 10-K borrowing interest expense plus D&A",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:DebtCurrent plus us-gaap:LongTermDebtNoncurrent",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "ko",
        "ticker": "KO",
        "name": "The Coca-Cola Company",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Consumer Staples",
        "industry": "Non-Alcoholic Beverages",
        "revenue": 47941.0,
        "ebitda": 14812.0,
        "net_income": 13107.0,
        "cash": 10270.0,
        "debt": 45492.0,
        "shares": 4313.0,
        "share_price": 76.82,
        **_arena_tier("red", "Iconic global beverage system with strong brand and distribution table presence."),
        "tags": {
            "industry_group": "consumer_staples_beverages",
            "strategic_tags": ["beverages", "brands", "distribution", "consumer staples"],
            "sensitive_sectors": ["consumer"],
            "jurisdiction": "US",
            "market_position": "global_beverage_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "KO",
            "0000021344",
            "0001628280-26-010047",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A; debt includes long-term debt and capital leases including current maturities, commercial paper, and other short-term borrowings.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts debt and capital leases plus commercial paper and other short-term borrowings",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "pg",
        "ticker": "PG",
        "name": "The Procter & Gamble Company",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Consumer Staples",
        "industry": "Household / Personal Care Brands",
        "revenue": 84284.0,
        "ebitda": 23298.0,
        "net_income": 15974.0,
        "cash": 9556.0,
        "debt": 34508.0,
        "shares": 2454.4,
        "share_price": 140.78,
        **_arena_tier("red", "Global consumer-staples brand portfolio with broad recognition and deal-table reach."),
        "tags": {
            "industry_group": "consumer_staples_brands",
            "strategic_tags": ["consumer staples", "brands", "household", "personal care"],
            "sensitive_sectors": ["consumer"],
            "jurisdiction": "US",
            "market_position": "global_consumer_brands_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "PG",
            "0000080424",
            "0000080424-25-000076",
            "FY ended 2025-06-30",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A; cash includes restricted cash; debt is current debt plus noncurrent long-term debt.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts cash, cash equivalents, and restricted cash",
                "debt": "SEC companyfacts us-gaap:DebtCurrent plus us-gaap:LongTermDebtNoncurrent",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "mcd",
        "ticker": "MCD",
        "name": "McDonald's Corporation",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Consumer Discretionary",
        "industry": "Quick Service Restaurants",
        "revenue": 26885.0,
        "ebitda": 14592.0,
        "net_income": 8563.0,
        "cash": 774.0,
        "debt": 40698.0,
        "shares": 716.4,
        "share_price": 272.72,
        **_arena_tier("red", "Globally iconic restaurant and franchise platform with a distinctive gameplay role."),
        "tags": {
            "industry_group": "quick_service_restaurants",
            "strategic_tags": ["restaurants", "franchising", "consumer", "real estate"],
            "sensitive_sectors": ["consumer"],
            "jurisdiction": "US",
            "market_position": "global_restaurant_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "MCD",
            "0000063908",
            "0000063908-26-000035",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus total D&A; debt is current plus noncurrent long-term debt and excludes lease liabilities.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts current plus noncurrent long-term debt",
                "shares": "SEC companyfacts diluted weighted-average shares, reported in millions",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "rtx",
        "ticker": "RTX",
        "name": "RTX Corporation",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Industrials",
        "industry": "Aerospace / Defense",
        "revenue": 88603.0,
        "ebitda": 13678.0,
        "net_income": 6732.0,
        "cash": 7435.0,
        "debt": 37904.0,
        "shares": 1356.4,
        "share_price": 179.41,
        **_arena_tier("red", "Aerospace and defense platform leader with strong strategic and regulatory table weight."),
        "tags": {
            "industry_group": "aerospace_defense",
            "strategic_tags": ["aerospace", "defense", "engines", "avionics"],
            "sensitive_sectors": ["defense", "aerospace"],
            "jurisdiction": "US",
            "market_position": "global_aerospace_defense_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "RTX",
            "0000101829",
            "0000101829-26-000006",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A; debt includes debt and capital leases including current maturities plus short-term borrowings.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts debt and capital leases including current maturities plus short-term borrowings",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "nflx",
        "ticker": "NFLX",
        "name": "Netflix, Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Communication Services",
        "industry": "Streaming Entertainment",
        "revenue": 45183.036,
        "ebitda": 13659.992,
        "net_income": 10981.201,
        "cash": 9033.681,
        "debt": 14462.836,
        "shares": 4343.863,
        "share_price": 81.56,
        **_arena_tier("gold", "Global streaming platform with iconic recognition and exceptional media-table impact."),
        "tags": {
            "industry_group": "streaming_content_platform",
            "strategic_tags": ["streaming", "content", "media", "subscriptions", "platform"],
            "sensitive_sectors": ["media", "content", "data"],
            "jurisdiction": "US",
            "market_position": "global_streaming_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "NFLX",
            "0001065280",
            "0001065280-26-000034",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A; debt is short-term plus noncurrent long-term debt. Shares and quote are post-split.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts short-term plus noncurrent long-term debt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "wmt",
        "ticker": "WMT",
        "name": "Walmart Inc.",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Consumer Staples",
        "industry": "Big-Box Retail / Grocery / Marketplace",
        "revenue": 713163.0,
        "ebitda": 44028.0,
        "net_income": 21893.0,
        "cash": 10727.0,
        "debt": 44762.0,
        "shares": 8022.0,
        "share_price": 117.74,
        **_arena_tier("gold", "Globally recognized retail and logistics platform with exceptional table reach."),
        "tags": {
            "industry_group": "big_box_retail",
            "strategic_tags": ["retail", "grocery", "logistics", "marketplace", "consumer staples"],
            "sensitive_sectors": ["consumer", "marketplace"],
            "jurisdiction": "US",
            "market_position": "global_retail_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "WMT",
            "0000104169",
            "0000104169-26-000055",
            "FY ended 2026-01-31",
            "FY2026 total revenue uses the SEC Revenues fact, including membership and other revenue. EBITDA is operating income plus depreciation/amortization/accretion. Debt is long-term debt plus short-term borrowings and excludes lease liabilities.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationAmortizationAndAccretionNet",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:LongTermDebt plus us-gaap:ShortTermBorrowings",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "pep",
        "ticker": "PEP",
        "name": "PepsiCo, Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Consumer Staples",
        "industry": "Beverages / Convenient Foods",
        "revenue": 93925.0,
        "ebitda": 14949.0,
        "net_income": 8240.0,
        "cash": 9159.0,
        "debt": 49182.0,
        "shares": 1373.0,
        "share_price": 142.15,
        **_arena_tier("red", "Global beverage and snacks leader with broad brand and distribution narratives."),
        "tags": {
            "industry_group": "consumer_staples_beverages_snacks",
            "strategic_tags": ["beverages", "snacks", "brands", "distribution", "consumer staples"],
            "sensitive_sectors": ["consumer"],
            "jurisdiction": "US",
            "market_position": "global_food_beverage_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "PEP",
            "0000077476",
            "0000077476-26-000007",
            "FY ended 2025-12-27",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A. Debt uses noncurrent long-term debt plus current debt so current maturities and short-term borrowings are included once.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:LongTermDebtNoncurrent plus us-gaap:DebtCurrent",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "jnj",
        "ticker": "JNJ",
        "name": "Johnson & Johnson",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Health Care",
        "industry": "Innovative Medicine / MedTech",
        "revenue": 94193.0,
        "ebitda": 32875.0,
        "net_income": 26804.0,
        "cash": 19709.0,
        "debt": 47938.0,
        "shares": 2429.4,
        "share_price": 228.17,
        **_arena_tier("gold", "Iconic diversified health-care platform with global recognition and strategic breadth."),
        "tags": {
            "industry_group": "healthcare_pharma_medtech",
            "strategic_tags": ["pharma", "medtech", "medical devices", "R&D", "healthcare"],
            "sensitive_sectors": ["healthcare", "biotechnology"],
            "jurisdiction": "US",
            "market_position": "global_healthcare_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "JNJ",
            "0000200406",
            "0000200406-26-000016",
            "FY ended 2025-12-28",
            "FY2025 revenue and net income tie to SEC facts. EBITDA is derived from pretax income less other nonoperating income plus D&A because a standardized operating-income fact is not available. Debt is current debt plus noncurrent long-term debt.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC pretax income less us-gaap:OtherNonoperatingIncomeExpense plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:DebtCurrent plus us-gaap:LongTermDebtNoncurrent",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "pfe",
        "ticker": "PFE",
        "name": "Pfizer Inc.",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Health Care",
        "industry": "Innovative Pharmaceuticals",
        "revenue": 62579.0,
        "ebitda": 20836.0,
        "net_income": 7771.0,
        "cash": 1142.0,
        "debt": 64795.0,
        "shares": 5713.0,
        "share_price": 25.69,
        **_arena_tier("red", "Globally recognized pharma platform with strong pipeline and portfolio transaction roles."),
        "tags": {
            "industry_group": "pharma_innovative",
            "strategic_tags": ["pharma", "vaccines", "oncology", "R&D", "biotechnology"],
            "sensitive_sectors": ["healthcare", "biotechnology"],
            "jurisdiction": "US",
            "market_position": "global_pharma_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "PFE",
            "0000078003",
            "0000078003-26-000026",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is derived from pretax income less other nonoperating expense plus D&A because the filing uses a functional expense presentation. Debt is current debt plus noncurrent long-term debt.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC pretax income less us-gaap:OtherNonoperatingIncomeExpense plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:DebtCurrent plus us-gaap:LongTermDebtNoncurrent",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "sbux",
        "ticker": "SBUX",
        "name": "Starbucks Corporation",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Consumer Discretionary",
        "industry": "Coffeehouse Retail",
        "revenue": 37184.4,
        "ebitda": 4708.1,
        "net_income": 1856.4,
        "cash": 3219.8,
        "debt": 16074.8,
        "shares": 1139.8,
        "share_price": 94.14,
        **_arena_tier("red", "Iconic global coffeehouse brand with a distinctive retail and loyalty role."),
        "tags": {
            "industry_group": "coffeehouse_retail",
            "strategic_tags": ["restaurants", "retail", "brands", "loyalty", "consumer"],
            "sensitive_sectors": ["consumer"],
            "jurisdiction": "US",
            "market_position": "global_coffeehouse_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "SBUX",
            "0000829224",
            "0000829224-25-000114",
            "FY ended 2025-09-28",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A. Cash uses the reported cash, cash equivalents, and restricted cash total. Debt is current plus noncurrent long-term debt and excludes leases.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts cash, cash equivalents, and restricted cash",
                "debt": "SEC companyfacts current plus noncurrent long-term debt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "nke",
        "ticker": "NKE",
        "name": "NIKE, Inc.",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Consumer Discretionary",
        "industry": "Athletic Footwear / Apparel",
        "revenue": 46309.0,
        "ebitda": 4477.0,
        "net_income": 3219.0,
        "cash": 7464.0,
        "debt": 7966.0,
        "shares": 1487.6,
        "share_price": 43.62,
        **_arena_tier("gold", "Iconic global athletic brand with exceptional recognition and consumer-table impact."),
        "tags": {
            "industry_group": "athletic_footwear_apparel",
            "strategic_tags": ["footwear", "apparel", "brands", "direct to consumer", "sports"],
            "sensitive_sectors": ["consumer"],
            "jurisdiction": "US",
            "market_position": "global_athletic_brand_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "NKE",
            "0000320187",
            "0000320187-25-000047",
            "FY ended 2025-05-31",
            "FY2025 core fields tie to SEC facts. EBITDA is pretax income less net interest income and other nonoperating income plus D&A. Debt includes long-term debt plus disclosed short-term borrowings and excludes leases.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC pretax income less net interest and other nonoperating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:LongTermDebt plus us-gaap:ShortTermBorrowings",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "isrg",
        "ticker": "ISRG",
        "name": "Intuitive Surgical, Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Health Care",
        "industry": "Robotic Surgery Systems",
        "revenue": 10064.7,
        "ebitda": 3558.7,
        "net_income": 2856.0,
        "cash": 3368.0,
        "debt": 0.0,
        "shares": 362.7,
        "share_price": 418.82,
        **_arena_tier("red", "Category-defining surgical robotics leader with a highly distinctive gameplay role."),
        "tags": {
            "industry_group": "medical_devices_robotics",
            "strategic_tags": ["medical devices", "robotics", "surgery", "installed base", "healthcare"],
            "sensitive_sectors": ["healthcare", "robotics"],
            "jurisdiction": "US",
            "market_position": "surgical_robotics_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "ISRG",
            "0001035267",
            "0001035267-26-000010",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus depreciation and intangible amortization. No interest-bearing debt was identified in the FY2025 SEC facts; operating lease liabilities are excluded.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:Depreciation plus us-gaap:AmortizationOfIntangibleAssets",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts review; no interest-bearing debt identified, leases excluded",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "dhr",
        "ticker": "DHR",
        "name": "Danaher Corporation",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Health Care",
        "industry": "Life Sciences / Diagnostics Tools",
        "revenue": 24568.0,
        "ebitda": 7137.0,
        "net_income": 3614.0,
        "cash": 4615.0,
        "debt": 18418.0,
        "shares": 716.1,
        "share_price": 186.64,
        **_arena_tier("red", "Global life-sciences and diagnostics tools leader with strong platform acquisition narratives."),
        "tags": {
            "industry_group": "healthcare_tools_diagnostics",
            "strategic_tags": ["life sciences", "diagnostics", "lab equipment", "bioprocessing", "healthcare"],
            "sensitive_sectors": ["healthcare", "biotechnology"],
            "jurisdiction": "US",
            "market_position": "global_tools_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "DHR",
            "0000313616",
            "0000313616-26-000062",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus depreciation and acquired-intangible amortization. Debt uses total long-term debt, including the small current maturity, and excludes leases.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:Depreciation plus us-gaap:AmortizationOfIntangibleAssets",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:LongTermDebt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "amgn",
        "ticker": "AMGN",
        "name": "Amgen Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Health Care",
        "industry": "Biotechnology / Innovative Medicines",
        "revenue": 36751.0,
        "ebitda": 14247.0,
        "net_income": 7711.0,
        "cash": 9129.0,
        "debt": 54604.0,
        "shares": 542.0,
        "share_price": 345.60,
        **_arena_tier("red", "Large biotechnology platform with strong pipeline, scale, and transaction narratives."),
        "tags": {
            "industry_group": "biotech_innovative",
            "strategic_tags": ["biotechnology", "pharma", "oncology", "rare disease", "R&D"],
            "sensitive_sectors": ["healthcare", "biotechnology"],
            "jurisdiction": "US",
            "market_position": "global_biotech_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "AMGN",
            "0000318154",
            "0000318154-26-000010",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A, including acquired-intangible amortization. Debt is current plus noncurrent long-term debt.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts current plus noncurrent long-term debt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "intu",
        "ticker": "INTU",
        "name": "Intuit Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Tax / Accounting / Financial Software",
        "revenue": 18831.0,
        "ebitda": 5732.0,
        "net_income": 3869.0,
        "cash": 2884.0,
        "debt": 5973.0,
        "shares": 283.0,
        "share_price": 301.98,
        **_arena_tier("red", "Category-leading tax and small-business software platform with strong deal narratives."),
        "tags": {
            "industry_group": "enterprise_tax_finance_software",
            "strategic_tags": ["software", "tax", "accounting", "fintech", "small business"],
            "sensitive_sectors": ["data", "financial_data"],
            "jurisdiction": "US",
            "market_position": "category_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "INTU",
            "0000896878",
            "0000896878-25-000035",
            "FY ended 2025-07-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus depreciation and total amortization. Cash excludes restricted customer funds; debt is total long-term debt and excludes leases.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:Depreciation plus us-gaap:AdjustmentForAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue; restricted customer funds excluded",
                "debt": "SEC companyfacts us-gaap:LongTermDebt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "txn",
        "ticker": "TXN",
        "name": "Texas Instruments Incorporated",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Analog / Embedded Semiconductors",
        "revenue": 17682.0,
        "ebitda": 8022.0,
        "net_income": 5001.0,
        "cash": 3225.0,
        "debt": 14048.0,
        "shares": 913.0,
        "share_price": 305.37,
        **_arena_tier("blue", "Mature analog semiconductor leader and dependable core supply-chain card."),
        "tags": {
            "industry_group": "semiconductor_analog",
            "strategic_tags": ["semiconductors", "analog", "embedded", "industrial", "automotive"],
            "sensitive_sectors": ["semiconductors", "industrial"],
            "jurisdiction": "US",
            "market_position": "analog_semiconductor_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "TXN",
            "0000097476",
            "0000097476-26-000059",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus depreciation and capitalized-software amortization. Debt is total long-term debt including current maturities; commercial paper was zero at year end.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:Depreciation plus us-gaap:CapitalizedComputerSoftwareAmortization1",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:LongTermDebt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "lrcx",
        "ticker": "LRCX",
        "name": "Lam Research Corporation",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Semiconductor Equipment",
        "revenue": 18435.591,
        "ebitda": 6287.245,
        "net_income": 5358.217,
        "cash": 6390.659,
        "debt": 4469.364,
        "shares": 1290.142,
        "share_price": 336.41,
        **_arena_tier("green", "Critical wafer-fabrication equipment specialist with a focused supply-chain role."),
        "tags": {
            "industry_group": "semiconductor_equipment",
            "strategic_tags": ["semiconductors", "equipment", "wafer fabrication", "manufacturing"],
            "sensitive_sectors": ["semiconductors", "industrial"],
            "jurisdiction": "US",
            "market_position": "equipment_category_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "LRCX",
            "0000707549",
            "0000707549-25-000075",
            "FY ended 2025-06-29",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A. Debt is current plus noncurrent long-term debt. Shares and quote use the post-split basis reported by the sources.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts current plus noncurrent long-term debt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "mu",
        "ticker": "MU",
        "name": "Micron Technology, Inc.",
        "market": "NASDAQ",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Memory Semiconductors",
        "revenue": 37378.0,
        "ebitda": 18122.0,
        "net_income": 8539.0,
        "cash": 9642.0,
        "debt": 11533.0,
        "shares": 1125.0,
        "share_price": 996.00,
        **_arena_tier("red", "Memory leader with strong AI-cycle, capacity, and supply-chain transaction narratives."),
        "tags": {
            "industry_group": "semiconductor_memory",
            "strategic_tags": ["semiconductors", "memory", "datacenter", "AI infrastructure", "manufacturing"],
            "sensitive_sectors": ["semiconductors", "AI"],
            "jurisdiction": "US",
            "market_position": "memory_semiconductor_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "MU",
            "0000723125",
            "0000723125-25-000028",
            "FY ended 2025-08-28",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A. The SEC total long-term debt fact includes current maturities; lease liabilities are excluded. The frozen quote produces a high implied equity value but is retained as the verified 2026-06-04 close.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationDepletionAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:LongTermDebt including current maturities",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "ups",
        "ticker": "UPS",
        "name": "United Parcel Service, Inc.",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Industrials",
        "industry": "Parcel Delivery / Logistics",
        "revenue": 88661.0,
        "ebitda": 11613.0,
        "net_income": 5572.0,
        "cash": 5887.0,
        "debt": 23585.0,
        "shares": 850.0,
        "share_price": 110.22,
        **_arena_tier("red", "Global parcel network with a distinctive logistics, density, and infrastructure role."),
        "tags": {
            "industry_group": "logistics_parcel_network",
            "strategic_tags": ["logistics", "parcel", "distribution", "air freight", "last mile"],
            "sensitive_sectors": ["logistics", "infrastructure"],
            "jurisdiction": "US",
            "market_position": "global_parcel_network_leader",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "UPS",
            "0001090727",
            "0001628280-26-008432",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus total D&A. Debt is the disclosed total long-term debt (us-gaap:LongTermDebt, which already includes current maturities) and excludes finance-lease and pension obligations. Current maturities are not added a second time; us-gaap:DebtCurrent is not summed in because it duplicates the current maturities already in LongTermDebt and contains finance-lease amounts that the lease-exclusion convention drops.",
            "medium",
            {
                "revenue": "SEC companyfacts us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:LongTermDebt (disclosed total, already inclusive of current maturities; us-gaap:DebtCurrent is excluded as a caveat-only reference because it double-counts current maturities and includes finance-lease amounts)",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
    {
        "id": "lmt",
        "ticker": "LMT",
        "name": "Lockheed Martin Corporation",
        "market": "NYSE",
        "currency": "USD",
        "sector": "Industrials",
        "industry": "Aerospace / Defense",
        "revenue": 75048.0,
        "ebitda": 9418.0,
        "net_income": 5017.0,
        "cash": 4121.0,
        "debt": 21700.0,
        "shares": 233.5,
        "share_price": 519.05,
        **_arena_tier("red", "Global defense prime with strong strategic, regulatory, and program-level table weight."),
        "tags": {
            "industry_group": "aerospace_defense",
            "strategic_tags": ["aerospace", "defense", "missiles", "space", "government"],
            "sensitive_sectors": ["defense", "aerospace"],
            "jurisdiction": "US",
            "market_position": "global_defense_prime",
            "state_linked": False,
        },
        "source_meta": _wave1_source(
            "LMT",
            "0000936468",
            "0001628280-26-004195",
            "FY ended 2025-12-31",
            "FY2025 core fields tie to SEC facts. EBITDA is operating income plus D&A. Debt is total long-term debt including current maturities and excludes lease liabilities.",
            "high",
            {
                "revenue": "SEC companyfacts us-gaap:Revenues",
                "ebitda": "Derived from SEC operating income plus us-gaap:DepreciationAndAmortization",
                "net_income": "SEC companyfacts us-gaap:NetIncomeLoss",
                "cash": "SEC companyfacts us-gaap:CashAndCashEquivalentsAtCarryingValue",
                "debt": "SEC companyfacts us-gaap:LongTermDebt",
                "shares": "SEC companyfacts diluted weighted-average shares",
                "share_price": "Yahoo Finance chart 2026-06-04 unadjusted close",
            },
        ),
    },
]


# V5.11.2 US Wave 3: extend the frozen real deck with the 55 reviewed Wave 3 US
# production cards (data gate applied to BKNG/SNPS/HSY share bases and the
# KR/TRV/HCA/BDX/MRSH reconciliation caveats). This keeps the wave-3 snapshot in
# its own reviewable module while preserving the single REAL_SEED_COMPANY_CARDS
# deck the loader and tests read. Total deck: 45 + 55 = 100 cards.
from modeling.ma.wave3_seed_deck import WAVE3_SEED_COMPANY_CARDS  # noqa: E402

REAL_SEED_COMPANY_CARDS.extend(WAVE3_SEED_COMPANY_CARDS)
