"""V5.1 frozen seed deck for Deal Studio company cards.

Figures are deterministic illustrative USD millions unless noted. They are not
live quotes, not a production curated deck, and not calibrated by runtime data.
"""

from __future__ import annotations

from typing import Any


def _source(notes: str) -> dict[str, str]:
    return {
        "source": "v5.1_seed_deck_sample",
        "source_document_or_provider": "fictional V5.1 dev/test fallback",
        "fiscal_period_or_as_of_date": "illustrative static deck as of 2026-06-04",
        "as_of_date": "2026-06-04",
        "notes": notes,
        "confidence": "fictional_dev_only",
    }


SEED_COMPANY_CARDS: list[dict[str, Any]] = [
    {
        "id": "atlas_software",
        "ticker": "ATLS",
        "name": "Atlas Software",
        "market": "US",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Enterprise Software",
        "revenue": 17800.0,
        "ebitda": 6200.0,
        "net_income": 4200.0,
        "cash": 7600.0,
        "debt": 5200.0,
        "shares": 1200.0,
        "share_price": 210.0,
        "tags": {
            "industry_group": "software",
            "strategic_tags": ["cloud", "enterprise", "subscription", "workflow"],
            "sensitive_sectors": [],
            "jurisdiction": "US",
            "market_position": "large_cap_leader",
            "state_linked": False,
        },
        "source_meta": _source("Fictional seed card extended from V5.0 sample."),
    },
    {
        "id": "beacon_payments",
        "ticker": "BCNP",
        "name": "Beacon Payments",
        "market": "US",
        "currency": "USD",
        "sector": "Financial Technology",
        "industry": "Payments Processing",
        "revenue": 11200.0,
        "ebitda": 3400.0,
        "net_income": 1850.0,
        "cash": 3100.0,
        "debt": 4100.0,
        "shares": 640.0,
        "share_price": 95.0,
        "tags": {
            "industry_group": "fintech_payments",
            "strategic_tags": ["payments", "merchant_services", "software", "data_network"],
            "sensitive_sectors": ["financial_infrastructure"],
            "jurisdiction": "US",
            "market_position": "scaled_challenger",
            "state_linked": False,
        },
        "source_meta": _source("Fictional seed card extended from V5.0 sample."),
    },
    {
        "id": "cedar_devices",
        "ticker": "CDRD",
        "name": "Cedar Devices",
        "market": "US",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Consumer Hardware",
        "revenue": 15400.0,
        "ebitda": 4500.0,
        "net_income": 2600.0,
        "cash": 4200.0,
        "debt": 2700.0,
        "shares": 900.0,
        "share_price": 78.0,
        "tags": {
            "industry_group": "hardware_devices",
            "strategic_tags": ["devices", "components", "manufacturing", "consumer"],
            "sensitive_sectors": [],
            "jurisdiction": "US",
            "market_position": "scaled_challenger",
            "state_linked": False,
        },
        "source_meta": _source("Fictional seed card extended from V5.0 sample."),
    },
    {
        "id": "delta_logistics",
        "ticker": "DLTL",
        "name": "Delta Logistics",
        "market": "US",
        "currency": "USD",
        "sector": "Industrials",
        "industry": "Logistics",
        "revenue": 9400.0,
        "ebitda": 2600.0,
        "net_income": 1450.0,
        "cash": 1200.0,
        "debt": 3500.0,
        "shares": 520.0,
        "share_price": 64.0,
        "tags": {
            "industry_group": "logistics",
            "strategic_tags": ["supply_chain", "transport", "distribution", "industrial_services"],
            "sensitive_sectors": [],
            "jurisdiction": "US",
            "market_position": "regional_leader",
            "state_linked": False,
        },
        "source_meta": _source("Fictional seed card extended from V5.0 sample."),
    },
    {
        "id": "evergreen_health",
        "ticker": "EVGH",
        "name": "Evergreen Health",
        "market": "US",
        "currency": "USD",
        "sector": "Healthcare",
        "industry": "Healthcare Services",
        "revenue": 6800.0,
        "ebitda": 1700.0,
        "net_income": 980.0,
        "cash": 900.0,
        "debt": 1900.0,
        "shares": 410.0,
        "share_price": 52.0,
        "tags": {
            "industry_group": "healthcare_services",
            "strategic_tags": ["healthcare_services", "provider_network", "care_delivery"],
            "sensitive_sectors": ["healthcare"],
            "jurisdiction": "US",
            "market_position": "regional_leader",
            "state_linked": False,
        },
        "source_meta": _source("Fictional seed card extended from V5.0 sample."),
    },
    {
        "id": "fulton_media",
        "ticker": "FLTN",
        "name": "Fulton Media",
        "market": "US",
        "currency": "USD",
        "sector": "Media",
        "industry": "Digital Media",
        "revenue": 3600.0,
        "ebitda": 980.0,
        "net_income": 540.0,
        "cash": 650.0,
        "debt": 850.0,
        "shares": 300.0,
        "share_price": 33.0,
        "tags": {
            "industry_group": "media",
            "strategic_tags": ["content", "advertising", "streaming", "consumer"],
            "sensitive_sectors": ["media"],
            "jurisdiction": "US",
            "market_position": "niche_challenger",
            "state_linked": False,
        },
        "source_meta": _source("Fictional seed card extended from V5.0 sample."),
    },
    {
        "id": "northstar_cloud",
        "ticker": "NSTC",
        "name": "Northstar Cloud",
        "market": "US",
        "currency": "USD",
        "sector": "Technology",
        "industry": "Cloud Infrastructure",
        "revenue": 13200.0,
        "ebitda": 3900.0,
        "net_income": 2100.0,
        "cash": 4800.0,
        "debt": 3600.0,
        "shares": 760.0,
        "share_price": 118.0,
        "tags": {
            "industry_group": "cloud_infrastructure",
            "strategic_tags": ["cloud", "infrastructure", "enterprise", "data_center"],
            "sensitive_sectors": ["cloud_infrastructure"],
            "jurisdiction": "US",
            "market_position": "scaled_challenger",
            "state_linked": False,
        },
        "source_meta": _source("Fictional seed card for V5.1 overlap tests."),
    },
    {
        "id": "harbor_retail",
        "ticker": "HBRR",
        "name": "Harbor Retail",
        "market": "US",
        "currency": "USD",
        "sector": "Consumer",
        "industry": "Omnichannel Retail",
        "revenue": 8200.0,
        "ebitda": 1100.0,
        "net_income": 620.0,
        "cash": 700.0,
        "debt": 2100.0,
        "shares": 360.0,
        "share_price": 41.0,
        "tags": {
            "industry_group": "retail",
            "strategic_tags": ["consumer", "omnichannel", "distribution", "loyalty"],
            "sensitive_sectors": [],
            "jurisdiction": "US",
            "market_position": "regional_leader",
            "state_linked": False,
        },
        "source_meta": _source("Fictional seed card for V5.1 cross-sector tests."),
    },
    {
        "id": "ironbridge_energy",
        "ticker": "IBEN",
        "name": "Ironbridge Energy",
        "market": "US",
        "currency": "USD",
        "sector": "Energy",
        "industry": "Energy Infrastructure",
        "revenue": 12100.0,
        "ebitda": 4100.0,
        "net_income": 1700.0,
        "cash": 1000.0,
        "debt": 6800.0,
        "shares": 690.0,
        "share_price": 58.0,
        "tags": {
            "industry_group": "energy_infrastructure",
            "strategic_tags": ["energy", "infrastructure", "industrial_services"],
            "sensitive_sectors": ["energy"],
            "jurisdiction": "US",
            "market_position": "regional_leader",
            "state_linked": False,
        },
        "source_meta": _source("Fictional seed card; viability tags are not used in EPS math."),
    },
    {
        "id": "quantum_chips",
        "ticker": "QCHP",
        "name": "Quantum Chips",
        "market": "US",
        "currency": "USD",
        "sector": "Semiconductors",
        "industry": "AI Semiconductors",
        "revenue": 7200.0,
        "ebitda": 2500.0,
        "net_income": 1350.0,
        "cash": 2900.0,
        "debt": 1200.0,
        "shares": 520.0,
        "share_price": 84.0,
        "tags": {
            "industry_group": "semiconductors",
            "strategic_tags": ["semiconductors", "hardware", "ai_infrastructure", "components"],
            "sensitive_sectors": ["semiconductors"],
            "jurisdiction": "US",
            "market_position": "niche_challenger",
            "state_linked": False,
        },
        "source_meta": _source("Fictional seed card; not a production curated deck."),
    },
]
